/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanAndSellRouteImport } from './routes/scan-and-sell'
import { Route as SalesTodayRouteImport } from './routes/sales-today'
import { Route as SalesAuditRouteImport } from './routes/sales-audit'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as InventoryAuditRouteImport } from './routes/inventory-audit'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CallCenterReportsRouteImport } from './routes/call-center-reports'
import { Route as CallCenterRouteImport } from './routes/call-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as InvoicesIdEditRouteImport } from './routes/invoices_.$id.edit'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanAndSellRoute = ScanAndSellRouteImport.update({
  id: '/scan-and-sell',
  path: '/scan-and-sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTodayRoute = SalesTodayRouteImport.update({
  id: '/sales-today',
  path: '/sales-today',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAuditRoute = SalesAuditRouteImport.update({
  id: '/sales-audit',
  path: '/sales-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAuditRoute = InventoryAuditRouteImport.update({
  id: '/inventory-audit',
  path: '/inventory-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterReportsRoute = CallCenterReportsRouteImport.update({
  id: '/call-center-reports',
  path: '/call-center-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterRoute = CallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdEditRoute = InvoicesIdEditRouteImport.update({
  id: '/invoices_/$id/edit',
  path: '/invoices/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-reports': typeof CallCenterReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-audit': typeof SalesAuditRoute
  '/sales-today': typeof SalesTodayRoute
  '/scan-and-sell': typeof ScanAndSellRoute
  '/settings': typeof SettingsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-reports': typeof CallCenterReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-audit': typeof SalesAuditRoute
  '/sales-today': typeof SalesTodayRoute
  '/scan-and-sell': typeof ScanAndSellRoute
  '/settings': typeof SettingsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices': typeof InvoicesIndexRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-reports': typeof CallCenterReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-audit': typeof SalesAuditRoute
  '/sales-today': typeof SalesTodayRoute
  '/scan-and-sell': typeof ScanAndSellRoute
  '/settings': typeof SettingsRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/invoices_/$id/edit': typeof InvoicesIdEditRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit-log'
    | '/auth'
    | '/call-center'
    | '/call-center-reports'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/inventory-audit'
    | '/products'
    | '/reports'
    | '/reset-password'
    | '/sales-audit'
    | '/sales-today'
    | '/scan-and-sell'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/'
    | '/invoices/$id/edit'
    | '/api/public/hooks/daily-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit-log'
    | '/auth'
    | '/call-center'
    | '/call-center-reports'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/inventory-audit'
    | '/products'
    | '/reports'
    | '/reset-password'
    | '/sales-audit'
    | '/sales-today'
    | '/scan-and-sell'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices'
    | '/invoices/$id/edit'
    | '/api/public/hooks/daily-backup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit-log'
    | '/auth'
    | '/call-center'
    | '/call-center-reports'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/inventory-audit'
    | '/products'
    | '/reports'
    | '/reset-password'
    | '/sales-audit'
    | '/sales-today'
    | '/scan-and-sell'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/'
    | '/invoices_/$id/edit'
    | '/api/public/hooks/daily-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  CallCenterRoute: typeof CallCenterRoute
  CallCenterReportsRoute: typeof CallCenterReportsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  InventoryAuditRoute: typeof InventoryAuditRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesAuditRoute: typeof SalesAuditRoute
  SalesTodayRoute: typeof SalesTodayRoute
  ScanAndSellRoute: typeof ScanAndSellRoute
  SettingsRoute: typeof SettingsRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  InvoicesIdEditRoute: typeof InvoicesIdEditRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-and-sell': {
      id: '/scan-and-sell'
      path: '/scan-and-sell'
      fullPath: '/scan-and-sell'
      preLoaderRoute: typeof ScanAndSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-today': {
      id: '/sales-today'
      path: '/sales-today'
      fullPath: '/sales-today'
      preLoaderRoute: typeof SalesTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-audit': {
      id: '/sales-audit'
      path: '/sales-audit'
      fullPath: '/sales-audit'
      preLoaderRoute: typeof SalesAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-audit': {
      id: '/inventory-audit'
      path: '/inventory-audit'
      fullPath: '/inventory-audit'
      preLoaderRoute: typeof InventoryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center-reports': {
      id: '/call-center-reports'
      path: '/call-center-reports'
      fullPath: '/call-center-reports'
      preLoaderRoute: typeof CallCenterReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center': {
      id: '/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof CallCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/$id/edit': {
      id: '/invoices_/$id/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof InvoicesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  CallCenterRoute: CallCenterRoute,
  CallCenterReportsRoute: CallCenterReportsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  InventoryAuditRoute: InventoryAuditRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesAuditRoute: SalesAuditRoute,
  SalesTodayRoute: SalesTodayRoute,
  ScanAndSellRoute: ScanAndSellRoute,
  SettingsRoute: SettingsRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  InvoicesIdEditRoute: InvoicesIdEditRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
