/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockIntakeRouteImport } from './routes/stock-intake'
import { Route as ShippingOrderRouteImport } from './routes/shipping-order'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanAndSellRouteImport } from './routes/scan-and-sell'
import { Route as SalesTodayRouteImport } from './routes/sales-today'
import { Route as SalesRangeRouteImport } from './routes/sales-range'
import { Route as SalesAuditRouteImport } from './routes/sales-audit'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProfitsRouteImport } from './routes/profits'
import { Route as ProfitScenariosRouteImport } from './routes/profit-scenarios'
import { Route as ProfitCalculatorRouteImport } from './routes/profit-calculator'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PoTrackingRouteImport } from './routes/po-tracking'
import { Route as PendingOperationsRouteImport } from './routes/pending-operations'
import { Route as InvoicesSystemNotesRouteImport } from './routes/invoices-system-notes'
import { Route as InventoryAuditRouteImport } from './routes/inventory-audit'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InTransitRouteImport } from './routes/in-transit'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CallCenterReportsRouteImport } from './routes/call-center-reports'
import { Route as CallCenterRouteImport } from './routes/call-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as DeliveryReceiptsIndexRouteImport } from './routes/delivery-receipts.index'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesDraftsRouteImport } from './routes/invoices.drafts'
import { Route as InvoicesArchiveRouteImport } from './routes/invoices.archive'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DeliveryReceiptsNewRouteImport } from './routes/delivery-receipts.new'
import { Route as DeliveryReceiptsIdRouteImport } from './routes/delivery-receipts.$id'
import { Route as ApiXChatRouteImport } from './routes/api/x-chat'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as InvoicesIdEditRouteImport } from './routes/invoices_.$id.edit'
import { Route as DeliveryReceiptsIdEditRouteImport } from './routes/delivery-receipts_.$id.edit'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'

const StockIntakeRoute = StockIntakeRouteImport.update({
  id: '/stock-intake',
  path: '/stock-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingOrderRoute = ShippingOrderRouteImport.update({
  id: '/shipping-order',
  path: '/shipping-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanAndSellRoute = ScanAndSellRouteImport.update({
  id: '/scan-and-sell',
  path: '/scan-and-sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTodayRoute = SalesTodayRouteImport.update({
  id: '/sales-today',
  path: '/sales-today',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRangeRoute = SalesRangeRouteImport.update({
  id: '/sales-range',
  path: '/sales-range',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAuditRoute = SalesAuditRouteImport.update({
  id: '/sales-audit',
  path: '/sales-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitsRoute = ProfitsRouteImport.update({
  id: '/profits',
  path: '/profits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitScenariosRoute = ProfitScenariosRouteImport.update({
  id: '/profit-scenarios',
  path: '/profit-scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitCalculatorRoute = ProfitCalculatorRouteImport.update({
  id: '/profit-calculator',
  path: '/profit-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PoTrackingRoute = PoTrackingRouteImport.update({
  id: '/po-tracking',
  path: '/po-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingOperationsRoute = PendingOperationsRouteImport.update({
  id: '/pending-operations',
  path: '/pending-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesSystemNotesRoute = InvoicesSystemNotesRouteImport.update({
  id: '/invoices-system-notes',
  path: '/invoices-system-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAuditRoute = InventoryAuditRouteImport.update({
  id: '/inventory-audit',
  path: '/inventory-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InTransitRoute = InTransitRouteImport.update({
  id: '/in-transit',
  path: '/in-transit',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterReportsRoute = CallCenterReportsRouteImport.update({
  id: '/call-center-reports',
  path: '/call-center-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterRoute = CallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryReceiptsIndexRoute = DeliveryReceiptsIndexRouteImport.update({
  id: '/delivery-receipts/',
  path: '/delivery-receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesDraftsRoute = InvoicesDraftsRouteImport.update({
  id: '/invoices/drafts',
  path: '/invoices/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesArchiveRoute = InvoicesArchiveRouteImport.update({
  id: '/invoices/archive',
  path: '/invoices/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryReceiptsNewRoute = DeliveryReceiptsNewRouteImport.update({
  id: '/delivery-receipts/new',
  path: '/delivery-receipts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryReceiptsIdRoute = DeliveryReceiptsIdRouteImport.update({
  id: '/delivery-receipts/$id',
  path: '/delivery-receipts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXChatRoute = ApiXChatRouteImport.update({
  id: '/api/x-chat',
  path: '/api/x-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdEditRoute = InvoicesIdEditRouteImport.update({
  id: '/invoices_/$id/edit',
  path: '/invoices/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryReceiptsIdEditRoute = DeliveryReceiptsIdEditRouteImport.update({
  id: '/delivery-receipts_/$id/edit',
  path: '/delivery-receipts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-reports': typeof CallCenterReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/in-transit': typeof InTransitRoute
  '/inventory': typeof InventoryRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/invoices-system-notes': typeof InvoicesSystemNotesRoute
  '/pending-operations': typeof PendingOperationsRoute
  '/po-tracking': typeof PoTrackingRoute
  '/products': typeof ProductsRoute
  '/profit-calculator': typeof ProfitCalculatorRoute
  '/profit-scenarios': typeof ProfitScenariosRoute
  '/profits': typeof ProfitsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-audit': typeof SalesAuditRoute
  '/sales-range': typeof SalesRangeRoute
  '/sales-today': typeof SalesTodayRoute
  '/scan-and-sell': typeof ScanAndSellRoute
  '/settings': typeof SettingsRoute
  '/shipping-order': typeof ShippingOrderRoute
  '/stock-intake': typeof StockIntakeRoute
  '/api/x-chat': typeof ApiXChatRoute
  '/delivery-receipts/$id': typeof DeliveryReceiptsIdRoute
  '/delivery-receipts/new': typeof DeliveryReceiptsNewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/archive': typeof InvoicesArchiveRoute
  '/invoices/drafts': typeof InvoicesDraftsRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/delivery-receipts/': typeof DeliveryReceiptsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/delivery-receipts/$id/edit': typeof DeliveryReceiptsIdEditRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-reports': typeof CallCenterReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/in-transit': typeof InTransitRoute
  '/inventory': typeof InventoryRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/invoices-system-notes': typeof InvoicesSystemNotesRoute
  '/pending-operations': typeof PendingOperationsRoute
  '/po-tracking': typeof PoTrackingRoute
  '/products': typeof ProductsRoute
  '/profit-calculator': typeof ProfitCalculatorRoute
  '/profit-scenarios': typeof ProfitScenariosRoute
  '/profits': typeof ProfitsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-audit': typeof SalesAuditRoute
  '/sales-range': typeof SalesRangeRoute
  '/sales-today': typeof SalesTodayRoute
  '/scan-and-sell': typeof ScanAndSellRoute
  '/settings': typeof SettingsRoute
  '/shipping-order': typeof ShippingOrderRoute
  '/stock-intake': typeof StockIntakeRoute
  '/api/x-chat': typeof ApiXChatRoute
  '/delivery-receipts/$id': typeof DeliveryReceiptsIdRoute
  '/delivery-receipts/new': typeof DeliveryReceiptsNewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/archive': typeof InvoicesArchiveRoute
  '/invoices/drafts': typeof InvoicesDraftsRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/delivery-receipts': typeof DeliveryReceiptsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/delivery-receipts/$id/edit': typeof DeliveryReceiptsIdEditRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-reports': typeof CallCenterReportsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/in-transit': typeof InTransitRoute
  '/inventory': typeof InventoryRoute
  '/inventory-audit': typeof InventoryAuditRoute
  '/invoices-system-notes': typeof InvoicesSystemNotesRoute
  '/pending-operations': typeof PendingOperationsRoute
  '/po-tracking': typeof PoTrackingRoute
  '/products': typeof ProductsRoute
  '/profit-calculator': typeof ProfitCalculatorRoute
  '/profit-scenarios': typeof ProfitScenariosRoute
  '/profits': typeof ProfitsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales-audit': typeof SalesAuditRoute
  '/sales-range': typeof SalesRangeRoute
  '/sales-today': typeof SalesTodayRoute
  '/scan-and-sell': typeof ScanAndSellRoute
  '/settings': typeof SettingsRoute
  '/shipping-order': typeof ShippingOrderRoute
  '/stock-intake': typeof StockIntakeRoute
  '/api/x-chat': typeof ApiXChatRoute
  '/delivery-receipts/$id': typeof DeliveryReceiptsIdRoute
  '/delivery-receipts/new': typeof DeliveryReceiptsNewRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/archive': typeof InvoicesArchiveRoute
  '/invoices/drafts': typeof InvoicesDraftsRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/delivery-receipts/': typeof DeliveryReceiptsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/delivery-receipts_/$id/edit': typeof DeliveryReceiptsIdEditRoute
  '/invoices_/$id/edit': typeof InvoicesIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit-log'
    | '/auth'
    | '/call-center'
    | '/call-center-reports'
    | '/customers'
    | '/dashboard'
    | '/diagnostics'
    | '/in-transit'
    | '/inventory'
    | '/inventory-audit'
    | '/invoices-system-notes'
    | '/pending-operations'
    | '/po-tracking'
    | '/products'
    | '/profit-calculator'
    | '/profit-scenarios'
    | '/profits'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/sales-audit'
    | '/sales-range'
    | '/sales-today'
    | '/scan-and-sell'
    | '/settings'
    | '/shipping-order'
    | '/stock-intake'
    | '/api/x-chat'
    | '/delivery-receipts/$id'
    | '/delivery-receipts/new'
    | '/email/unsubscribe'
    | '/invoices/$id'
    | '/invoices/archive'
    | '/invoices/drafts'
    | '/invoices/new'
    | '/delivery-receipts/'
    | '/invoices/'
    | '/api/public/push-dispatch'
    | '/delivery-receipts/$id/edit'
    | '/invoices/$id/edit'
    | '/lovable/email/suppression'
    | '/api/public/hooks/daily-backup'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit-log'
    | '/auth'
    | '/call-center'
    | '/call-center-reports'
    | '/customers'
    | '/dashboard'
    | '/diagnostics'
    | '/in-transit'
    | '/inventory'
    | '/inventory-audit'
    | '/invoices-system-notes'
    | '/pending-operations'
    | '/po-tracking'
    | '/products'
    | '/profit-calculator'
    | '/profit-scenarios'
    | '/profits'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/sales-audit'
    | '/sales-range'
    | '/sales-today'
    | '/scan-and-sell'
    | '/settings'
    | '/shipping-order'
    | '/stock-intake'
    | '/api/x-chat'
    | '/delivery-receipts/$id'
    | '/delivery-receipts/new'
    | '/email/unsubscribe'
    | '/invoices/$id'
    | '/invoices/archive'
    | '/invoices/drafts'
    | '/invoices/new'
    | '/delivery-receipts'
    | '/invoices'
    | '/api/public/push-dispatch'
    | '/delivery-receipts/$id/edit'
    | '/invoices/$id/edit'
    | '/lovable/email/suppression'
    | '/api/public/hooks/daily-backup'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit-log'
    | '/auth'
    | '/call-center'
    | '/call-center-reports'
    | '/customers'
    | '/dashboard'
    | '/diagnostics'
    | '/in-transit'
    | '/inventory'
    | '/inventory-audit'
    | '/invoices-system-notes'
    | '/pending-operations'
    | '/po-tracking'
    | '/products'
    | '/profit-calculator'
    | '/profit-scenarios'
    | '/profits'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/sales-audit'
    | '/sales-range'
    | '/sales-today'
    | '/scan-and-sell'
    | '/settings'
    | '/shipping-order'
    | '/stock-intake'
    | '/api/x-chat'
    | '/delivery-receipts/$id'
    | '/delivery-receipts/new'
    | '/email/unsubscribe'
    | '/invoices/$id'
    | '/invoices/archive'
    | '/invoices/drafts'
    | '/invoices/new'
    | '/delivery-receipts/'
    | '/invoices/'
    | '/api/public/push-dispatch'
    | '/delivery-receipts_/$id/edit'
    | '/invoices_/$id/edit'
    | '/lovable/email/suppression'
    | '/api/public/hooks/daily-backup'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  CallCenterRoute: typeof CallCenterRoute
  CallCenterReportsRoute: typeof CallCenterReportsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  InTransitRoute: typeof InTransitRoute
  InventoryRoute: typeof InventoryRoute
  InventoryAuditRoute: typeof InventoryAuditRoute
  InvoicesSystemNotesRoute: typeof InvoicesSystemNotesRoute
  PendingOperationsRoute: typeof PendingOperationsRoute
  PoTrackingRoute: typeof PoTrackingRoute
  ProductsRoute: typeof ProductsRoute
  ProfitCalculatorRoute: typeof ProfitCalculatorRoute
  ProfitScenariosRoute: typeof ProfitScenariosRoute
  ProfitsRoute: typeof ProfitsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesAuditRoute: typeof SalesAuditRoute
  SalesRangeRoute: typeof SalesRangeRoute
  SalesTodayRoute: typeof SalesTodayRoute
  ScanAndSellRoute: typeof ScanAndSellRoute
  SettingsRoute: typeof SettingsRoute
  ShippingOrderRoute: typeof ShippingOrderRoute
  StockIntakeRoute: typeof StockIntakeRoute
  ApiXChatRoute: typeof ApiXChatRoute
  DeliveryReceiptsIdRoute: typeof DeliveryReceiptsIdRoute
  DeliveryReceiptsNewRoute: typeof DeliveryReceiptsNewRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesArchiveRoute: typeof InvoicesArchiveRoute
  InvoicesDraftsRoute: typeof InvoicesDraftsRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  DeliveryReceiptsIndexRoute: typeof DeliveryReceiptsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  DeliveryReceiptsIdEditRoute: typeof DeliveryReceiptsIdEditRoute
  InvoicesIdEditRoute: typeof InvoicesIdEditRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-intake': {
      id: '/stock-intake'
      path: '/stock-intake'
      fullPath: '/stock-intake'
      preLoaderRoute: typeof StockIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-order': {
      id: '/shipping-order'
      path: '/shipping-order'
      fullPath: '/shipping-order'
      preLoaderRoute: typeof ShippingOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-and-sell': {
      id: '/scan-and-sell'
      path: '/scan-and-sell'
      fullPath: '/scan-and-sell'
      preLoaderRoute: typeof ScanAndSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-today': {
      id: '/sales-today'
      path: '/sales-today'
      fullPath: '/sales-today'
      preLoaderRoute: typeof SalesTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-range': {
      id: '/sales-range'
      path: '/sales-range'
      fullPath: '/sales-range'
      preLoaderRoute: typeof SalesRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-audit': {
      id: '/sales-audit'
      path: '/sales-audit'
      fullPath: '/sales-audit'
      preLoaderRoute: typeof SalesAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profits': {
      id: '/profits'
      path: '/profits'
      fullPath: '/profits'
      preLoaderRoute: typeof ProfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-scenarios': {
      id: '/profit-scenarios'
      path: '/profit-scenarios'
      fullPath: '/profit-scenarios'
      preLoaderRoute: typeof ProfitScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-calculator': {
      id: '/profit-calculator'
      path: '/profit-calculator'
      fullPath: '/profit-calculator'
      preLoaderRoute: typeof ProfitCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po-tracking': {
      id: '/po-tracking'
      path: '/po-tracking'
      fullPath: '/po-tracking'
      preLoaderRoute: typeof PoTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-operations': {
      id: '/pending-operations'
      path: '/pending-operations'
      fullPath: '/pending-operations'
      preLoaderRoute: typeof PendingOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices-system-notes': {
      id: '/invoices-system-notes'
      path: '/invoices-system-notes'
      fullPath: '/invoices-system-notes'
      preLoaderRoute: typeof InvoicesSystemNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-audit': {
      id: '/inventory-audit'
      path: '/inventory-audit'
      fullPath: '/inventory-audit'
      preLoaderRoute: typeof InventoryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-transit': {
      id: '/in-transit'
      path: '/in-transit'
      fullPath: '/in-transit'
      preLoaderRoute: typeof InTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center-reports': {
      id: '/call-center-reports'
      path: '/call-center-reports'
      fullPath: '/call-center-reports'
      preLoaderRoute: typeof CallCenterReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center': {
      id: '/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof CallCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-receipts/': {
      id: '/delivery-receipts/'
      path: '/delivery-receipts'
      fullPath: '/delivery-receipts/'
      preLoaderRoute: typeof DeliveryReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/drafts': {
      id: '/invoices/drafts'
      path: '/invoices/drafts'
      fullPath: '/invoices/drafts'
      preLoaderRoute: typeof InvoicesDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/archive': {
      id: '/invoices/archive'
      path: '/invoices/archive'
      fullPath: '/invoices/archive'
      preLoaderRoute: typeof InvoicesArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-receipts/new': {
      id: '/delivery-receipts/new'
      path: '/delivery-receipts/new'
      fullPath: '/delivery-receipts/new'
      preLoaderRoute: typeof DeliveryReceiptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-receipts/$id': {
      id: '/delivery-receipts/$id'
      path: '/delivery-receipts/$id'
      fullPath: '/delivery-receipts/$id'
      preLoaderRoute: typeof DeliveryReceiptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x-chat': {
      id: '/api/x-chat'
      path: '/api/x-chat'
      fullPath: '/api/x-chat'
      preLoaderRoute: typeof ApiXChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/$id/edit': {
      id: '/invoices_/$id/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof InvoicesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-receipts_/$id/edit': {
      id: '/delivery-receipts_/$id/edit'
      path: '/delivery-receipts/$id/edit'
      fullPath: '/delivery-receipts/$id/edit'
      preLoaderRoute: typeof DeliveryReceiptsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  CallCenterRoute: CallCenterRoute,
  CallCenterReportsRoute: CallCenterReportsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  InTransitRoute: InTransitRoute,
  InventoryRoute: InventoryRoute,
  InventoryAuditRoute: InventoryAuditRoute,
  InvoicesSystemNotesRoute: InvoicesSystemNotesRoute,
  PendingOperationsRoute: PendingOperationsRoute,
  PoTrackingRoute: PoTrackingRoute,
  ProductsRoute: ProductsRoute,
  ProfitCalculatorRoute: ProfitCalculatorRoute,
  ProfitScenariosRoute: ProfitScenariosRoute,
  ProfitsRoute: ProfitsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesAuditRoute: SalesAuditRoute,
  SalesRangeRoute: SalesRangeRoute,
  SalesTodayRoute: SalesTodayRoute,
  ScanAndSellRoute: ScanAndSellRoute,
  SettingsRoute: SettingsRoute,
  ShippingOrderRoute: ShippingOrderRoute,
  StockIntakeRoute: StockIntakeRoute,
  ApiXChatRoute: ApiXChatRoute,
  DeliveryReceiptsIdRoute: DeliveryReceiptsIdRoute,
  DeliveryReceiptsNewRoute: DeliveryReceiptsNewRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesArchiveRoute: InvoicesArchiveRoute,
  InvoicesDraftsRoute: InvoicesDraftsRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  DeliveryReceiptsIndexRoute: DeliveryReceiptsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  DeliveryReceiptsIdEditRoute: DeliveryReceiptsIdEditRoute,
  InvoicesIdEditRoute: InvoicesIdEditRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
